### ISSUE TITLE
Thoughts on appCache Nanny integration to work around some of the intrinsic app-cache browser issues

### ISSUE THREAD

**Issue by nigel-v-thomas** [realityforge/gwt-appcache#12]
Hi,

Can I check if gwt-appcache has any work arounds for the many issues with app-cache implementations in browsers, as detailed by Jake Archibald on the subject [Application Cache is a Douchebag](http://alistapart.com/article/application-cache-is-a-douchebag)?

I have recently come [across appCache Nanny](https://github.com/gr2m/appcache-nanny) which provides some workarounds - assuming that it be relatively easy to integrate(?), what are your thoughts on integration, assuming I contribute it, would it be useful?

Best wishes,
Nigel

**Comment by realityforge** [comment]
gwt-appcache simplifies integration of Appcache into a gwt app and removes many of the complexities of integrating appcache. It does this because the gwt compiler can determine all the required assets and manage the manifest automagically, in particular when it needs to be updated. This addresses some of the complaints in the "Application Cache is a Douchebag" article but most of the complaints are that AppCache is not a generic caching mechanism. i.e. AppCache is great at caching application code but very poor at caching application data. (For application data  caching we tend to use LocalStorage and/or IndexDB/WebSQL so don't run into these issues.)

So is there any specific feature that is part of appcache nanny that you think would be of value to add to gwt-appcache? From a brief look at it, appCache Nanny seems not to offer anything needed by gwt-appcache.

**Comment by nigel-v-thomas** [comment]
Thanks for sharing your thoughts on this, I am investigating the issue now, with a view to test across browsers. However, on trying to use this on our application which uses GWT 2.7.0, I get a ```Unable to locate permutations file: /example/permutations.xml``` exception. I have followed your instructions on the FAQ, to no avail, please review the pull request where I have reproduced the same issue. Thanks Nigel

**Comment by realityforge** [comment]
great to see you got over the build problems. I am going to close this issue as there does not seem to be any action required. Feel free to open it again if you want anything done or need more infromation. Thanks!
