### ISSUE TITLE
Add unique id to the generated ".appcache" file

### ISSUE THREAD

**Issue by phnmnm** [realityforge/gwt-appcache#14]
I used Gwt2Go before, which added a unique ID to the manifest file everytime it got written.
So each time I build my WAR I had a different file which updated my offline application.

see [Gwt2Go](https://github.com/lpelov/gwt2go/blob/master/gwt2go/src/com/gwt2go/dev/linker/ManifestLinker.java)

`tManifest = tManifest.replace("$UNIQUEID$", (new Date()).getTime() + "." + Math.random());`

Is that possible too or do I have to edit the file by myself?

**Comment by phnmnm** [comment]
Solved it with Maven ... but still would be a nice feature?!?

**Comment by realityforge** [comment]
The project originally had that feature but it was removed. Usually it is not needed as if you change the code and it results in a change to javascript then the manifest will have different contents due to change sha1 of generated javascript files.

This is a useful feature if you update assets, reference them in the manifest and their names are not perfectly cacheable. In this scenario we tend to touch the manifest at the end of our sass compile. HTH

**Comment by phnmnm** [comment]
Seems legit! Thx for the explanation.

Works perfectly your lib.

Still on a mobile device with ZetaKey browser appcache is a b****.
